### ISSUE TITLE
Compile Error with an older Win10SDK

### ISSUE THREAD

**Issue by ColderCoder** [danielkrupinski/Osiris#1012]
I have the latest VS2019 (16.4.3). Got Error C1082 (unable to open include file "docobj.h") with WinSDK_10.0.17763.0. The error was resolved after I upgraded to 10.0.18362.0.
New to C++ compiler. Don't know why, just report what I see.

**Comment by xAkiraMiura** [comment]
Did you modify the project at all or just cloned/downloaded it from github?
This could have happened due to the .vcxproj getting modified (potentially by opening it with an older version of VS).
Check in the project settings if the version is **v141** or v**142**.
_p.s. you're using the VC++ compiler_

**Comment by Lolicop** [comment]
I'm also getting compile errors.
![image](https://user-images.githubusercontent.com/60243434/73033602-2f278100-3e08-11ea-8569-86021810e4a0.png)

I've tried uninstalling it completely and re downloading the project but get the same errors.

**Comment by notgoodusename** [comment]
try getting the lastest sdk

**Comment by xAkiraMiura** [comment]
I just cloned a fresh copy, I have no errors, there might be a problem with your VS2019 install. 
**WITHOUT UNINSTALLING**: try running the installer again and adding the C++ stuff.

Also make sure you are on `Release x86`

**Comment by thomas0aotian** [comment]
@Lolicop syntax errors are def coding language problem, like for example utf8 chinese characters sometimes will export this kinda error

**Comment by xAkiraMiura** [comment]
> 
> 
> @Lolicop syntax errors are def coding language problem, like for example utf8 chinese characters sometimes will export this kinda error

not having a certain dependancy can cause code upstream to have errors, if you have an exact copy of the code and it works on our machines you are missing a dependancy.
using unicode characters in an acsii string won't result in a syntax error, [it will just be moon runes](https://en.wikipedia.org/wiki/Mojibake).

**Comment by thomas0aotian** [comment]
@xAkiraMiura if only u have any experiences of coding in other languages then u wouldn't say such a thing

**Comment by xAkiraMiura** [comment]
I do have experience with legacy programs writen in non-latin languages, please, stop being ignorant just based on my nationality.
let me explain to you how this works.

In ASCII, all characters are always 1 byte in size. In unicode, characters can be anywhere from 1 to 4 bytes in size. When you attempt to put a 4 byte long unicode character into ASCII (char) it sees it as 4 characters. if the character code was a high number, it will wrap around to a number within the range of 0 to 2^8 and get interpreted as a different letter. We don't speak in wrap arounded numbers converted to letters so this appears to be random.

If you have every had someone with a Unicode name try to draw on your ESP, either they will display as random characters or nothing at all depending on the font.

**stop trying to start a flame war, you don't know what your saying so don't talk.**

**Comment by ColderCoder** [comment]
> Did you modify the project at all or just cloned/downloaded it from github?
> This could have happened due to the .vcxproj getting modified (potentially by opening it with an older version of VS).
> Check in the project settings if the version is **v141** or **v142**.
> _p.s. you're using the VC++ compiler_

Nope. Just download Zip and extract. And I have v142 installed. After I updated win10sdk, I opened the same project and everything was fine. If anyone else has the same environment (v142 and an older SDK) gets the same error, I think you may address the "newest" SDK version in readme? Or it's all my fault, just close the issue.

**Comment by thomas0aotian** [comment]
@xAkiraMiura 
[Possible solution ](https://docs.microsoft.com/en-us/cpp/build/reference/utf-8-set-source-and-executable-character-sets-to-utf-8?redirectedfrom=MSDN&view=vs-2019)

[Specific explanation in Chinese ](https://blog.caock.net/zh/visual-studio-utf-8%E7%BC%96%E7%A0%81%E4%B8%AD%E6%96%87%E6%B3%A8%E9%87%8A%E5%AF%BC%E8%87%B4%E7%9A%84%E7%BD%95%E8%A7%81%E9%97%AE%E9%A2%98/)
Lmao there's lot a doc out there saying that utf8 non latin compiling in vs may return errors. 
And stop being like u are the only one knows what u were saying.  Big boomer:-1:

**Comment by xAkiraMiura** [comment]
# stop derailing threads, the problem has been solved, no need to continue.
@ColderCoder you have to close the issue, we can't

**Warning: Potential Security Risk Ahead
Firefox detected an issue and did not continue to blog.caock.net.**

nice website you got there, would be a shame if the developers were too brain dead to update the certificate.

if your relying on a compiler switch to get your code to work in a different language then there is a big problem. maybe you should just use wchar_t as it was indended. All Windows.h methods have a W varient to support unicode. also using the utf-8 switch doesn't work half the time.

Small script kiddie 👎
